from django.db import models





class Temp_CarDeclaration(models.Model):
    empid = models.CharField(max_length=50, blank=True, null=True)
    clc = models.BooleanField(blank=True, null=True)
    have_car = models.BooleanField(blank=True, null=True)
    own_car = models.BooleanField(blank=True, null=True)
    cc = models.CharField(max_length=50, blank=True, null=True)
    carregdt = models.DateField(blank=True, null=True)
    no_driver = models.CharField(max_length=50, blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    registration = models.CharField(max_length=20, blank=True, null=True)
    
    DeclarationNo = models.CharField(max_length=50, blank=True, null=True)
    Integrated = models.BooleanField(blank=True, null=True)
    change_mark = models.BooleanField(blank=True, null=True)

class Temp_HRA(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)
   
    d_houserentstartdt = models.DateField(blank=True, null=True)
    d_rentpermonth = models.BigIntegerField(blank=True, null=True)
    d_landlordsname = models.CharField(max_length=50, blank=True, null=True)
    d_landlordspannum = models.CharField(max_length=50, blank=True, null=True)
    d_landlordscontact = models.CharField(max_length=30, blank=True, null=True)
    d_citytype = models.CharField(max_length=30, blank=True, null=True)
    d_landlordsaddress = models.CharField(max_length=100, blank=True, null=True)
    d_rentaddress = models.CharField(max_length=100, blank=True, null=True)
    d_pincode = models.BigIntegerField(blank=True, null=True)

    saveddate = models.DateTimeField(blank=True, null=True)

class Temp_Income(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)
    
    d_selfloan_dt = models.DateTimeField(blank=True, null=True, default=None)
    d_selfoccupiedloanint = models.BigIntegerField(blank=True, null=True)
    d_selflendername = models.CharField(max_length=200, blank=True, null=True)
    d_selflenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_selfotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_selfotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_letannuallettable = models.BigIntegerField(blank=True, null=True)
    d_letmunicipalprotax = models.BigIntegerField(blank=True, null=True)
    d_lethomeloaninterest = models.BigIntegerField(blank=True, null=True)
    d_letincomeloss = models.BigIntegerField(blank=True, null=True)
    d_letstanderedded = models.BigIntegerField(blank=True, null=True)
    d_letlendername = models.CharField(max_length=200, blank=True, null=True)
    d_letlenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_letotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_letotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_80eeloadsanctiondt = models.DateTimeField(blank=True, null=True)
    d_80eeloanammount = models.BigIntegerField(blank=True, null=True)
    d_80eepropertyvalue = models.BigIntegerField(blank=True, null=True)
    d_80eehomeloanint = models.BigIntegerField(blank=True, null=True)
    d_80eelendername = models.CharField(max_length=200, blank=True, null=True)
    d_80eelenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_80eeotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_80eeotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_80eealoadsanctiondt = models.DateTimeField(blank=True, null=True)
    d_80eeahaveproperty = models.CharField(max_length=20, blank=True, null=True)
    d_80eeaprpertyvalue = models.BigIntegerField(blank=True, null=True)
    d_80eeaeligibility = models.CharField(max_length=20, blank=True, null=True)

    d_80ttaotherincome = models.BigIntegerField( blank=True, null=True)
    d_80ttasavinginterest = models.BigIntegerField( blank=True, null=True)

    saveddate = models.DateTimeField(blank=True, null=True)

class Temp_80Other(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)

    
    d_80dselfinsurance = models.BigIntegerField(blank=True, null=True)
    d_80dnonseniorinsurance = models.BigIntegerField( blank=True, null=True)
    d_80dseniorinsurance = models.BigIntegerField(blank=True, null=True)
    d_80dpreventivecheckup = models.BigIntegerField(blank=True, null=True)
    
    d_80dillnesstype = models.CharField(max_length=100, blank=True, null=True)
    d_80ddbmedicalfield = models.CharField(max_length=100, blank=True, null=True)
    d_80ddbmedicaltreatment = models.BigIntegerField(blank=True, null=True)

    d_80eeducation_dt = models.DateTimeField(blank=True, null=True, default=None)
    d_80eeducationint = models.BigIntegerField(blank=True, null=True)

    d_80uselfdisable = models.BigIntegerField(blank=True, null=True)
    d_80dddependdisable = models.BigIntegerField(blank=True, null=True)

    d_80eebvehicltype = models.CharField(max_length=50, blank=True, null=True)
    d_80eebloansactiondt = models.DateTimeField(blank=True, null=True)
    d_80eebcarint = models.BigIntegerField( blank=True, null=True)

    d_80ccbselfcontrib = models.BigIntegerField(blank=True, null=True)
    d_80ccbprannum = models.BigIntegerField(blank=True, null=True)

    saveddate = models.DateTimeField(blank=True, null=True)

class Temp_80DDed(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)

    
    d_80clifeinsurance = models.BigIntegerField( blank=True, null=True)
    d_80c5yrtimedeposit = models.BigIntegerField(blank=True, null=True)
    d_80culip =  models.BigIntegerField(blank=True, null=True)
    d_80cnscsubscription = models.BigIntegerField(blank=True, null=True)
    d_80cnscint = models.BigIntegerField( blank=True, null=True)
    d_80cpublicpfund = models.BigIntegerField( blank=True, null=True)
    d_80chouseloan = models.BigIntegerField(blank=True, null=True)
    d_80ctuitionfee = models.BigIntegerField(blank=True, null=True)
    d_80cmutualfund = models.BigIntegerField( blank=True, null=True)
    d_80ctermdposite = models.BigIntegerField(blank=True, null=True)
    d_80csuksam = models.BigIntegerField(blank=True, null=True)

    saveddate = models.DateTimeField(blank=True, null=True)

class Temp_Prev(models.Model):

    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)

    d_prevsalary = models.BigIntegerField( blank=True, null=True)
    d_prevprofund = models.BigIntegerField( blank=True, null=True)
    d_prevprofessionaltax = models.BigIntegerField(blank=True, null=True)
    d_previncometax = models.BigIntegerField(blank=True, null=True)
    

    saveddate = models.DateTimeField(blank=True, null=True)
    






class CarDeclaration(models.Model):
    empid = models.CharField(max_length=50, blank=True, null=True)
    clc = models.BooleanField(blank=True, null=True)
    have_car = models.BooleanField(blank=True, null=True)
    own_car = models.BooleanField(blank=True, null=True)
    cc = models.CharField(max_length=50, blank=True, null=True)
    carregdt = models.DateField(blank=True, null=True)
    no_driver = models.CharField(max_length=50, blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    registration = models.CharField(max_length=20, blank=True, null=True)

    DeclarationNo = models.CharField(max_length=50, blank=True, null=True)
    Integrated = models.BooleanField(blank=True, null=True)
    change_mark = models.BooleanField(blank=True, null=True)


class EmployeeDetail(models.Model):

    empid = models.CharField(max_length=20, null=True)
    empname = models.TextField(blank=True, null=True)
    empemail = models.EmailField(blank=True, null=True)
    emppan = models.CharField(max_length=12, blank=True, null=True)
    empmobile = models.CharField(max_length=50, blank=True, null=True)
    empdob = models.DateField(blank=True, null=True)
    empdoj = models.DateField(blank=True, null=True)
    fathername = models.CharField(max_length=50, blank=True, null=True)

    emp_perner = models.CharField(max_length=50, blank=True, null=True)
    emp_password = models.CharField(max_length=50, blank=True, null=True)
    nRent_doc = models.IntegerField(blank=True, null=True)
    n80C_doc = models.IntegerField(blank=True, null=True)
    n80D_doc = models.IntegerField(blank=True, null=True)
    n80DD_doc = models.IntegerField(blank=True, null=True)
    n80E_doc = models.IntegerField(blank=True, null=True)
    n80DDB_doc = models.IntegerField(blank=True, null=True)
    n80EE_doc = models.IntegerField(blank=True, null=True)
    n80U_doc = models.IntegerField(blank=True, null=True)
    n80CCG_doc = models.IntegerField(blank=True, null=True)
    n80TTA_doc = models.IntegerField(blank=True, null=True)
    nOth_doc = models.IntegerField(blank=True, null=True)
    nhLoan_doc = models.IntegerField(blank=True, null=True)
    nLetout_doc = models.IntegerField(blank=True, null=True)
    nPreEmp_doc = models.IntegerField(blank=True, null=True)
    nall_doc = models.IntegerField(blank=True, null=True)
    sub1 = models.BooleanField(blank=True, null=True)
    CreatedDate = models.DateTimeField(blank=True, null=True)
    LastDate = models.DateTimeField(blank=True, null=True)
    
    gender = models.CharField(max_length=10, blank=True, null=True)
    nNps_doc = models.IntegerField(blank=True, null=True)
    designation = models.TextField(blank=True, null=True)
    PwdAttempt = models.IntegerField(blank=True, null=True)
    passworddt = models.DateTimeField(blank=True, null=True)
    nPan_doc = models.IntegerField(blank=True, null=True)
    nMed_doc = models.IntegerField(blank=True, null=True)
    nLta_doc = models.IntegerField(blank=True, null=True)
    nVehicle_doc = models.IntegerField(blank=True, null=True)
    n80CCD1_doc = models.IntegerField(blank=True, null=True)
    n80CSukSam_doc = models.IntegerField(blank=True, null=True)
    n80CCCC_doc = models.IntegerField(blank=True, null=True)
    n80CPODeposit_doc = models.IntegerField(blank=True, null=True)
    n80CULIP_doc = models.IntegerField(blank=True, null=True)
    n80CNSCViii_doc = models.IntegerField(blank=True, null=True)
    n80CIntNSC_doc = models.IntegerField(blank=True, null=True)
    n80CPPF_doc = models.IntegerField(blank=True, null=True)
    n80CHouseLoan_doc = models.IntegerField(blank=True, null=True)
    n80CTutionFee_doc = models.IntegerField(blank=True, null=True)
    n80CMfund_doc = models.IntegerField(blank=True, null=True)
    n12b_doc = models.IntegerField(blank=True, null=True)
    updatedDate = models.DateTimeField(blank=True, null=True)
    n12bb_doc = models.IntegerField(blank=True, null=True)
    Company_Name = models.CharField(max_length=50, blank=True, null=True)
    nhra_doc = models.IntegerField(blank=True, null=True)
    Worker_ID = models.CharField(max_length=50, blank=True, null=True)
    Sepration_Approved_Date = models.DateField(blank=True, null=True)
    LDE = models.DateField(blank=True, null=True)
    Band = models.CharField(max_length=2, blank=True, null=True)
    PWD = models.CharField(max_length=4, blank=True, null=True)
    Updated_Date = models.DateField(blank=True, null=True)
    Action = models.CharField(max_length=1, blank=True, null=True)
    Status = models.CharField(max_length=1, blank=True, null=True)
    UpdateTimestamp = models.DateTimeField(blank=True, null=True)
    AR = models.CharField(max_length=1, blank=True, null=True)
    filename = models.CharField(max_length=50, blank=True, null=True)
    n80EEA_doc = models.IntegerField(blank=True, null=True)
    n80EEB_doc = models.IntegerField(blank=True, null=True)
    blnPFDoc = models.BooleanField(blank=True, null=True)

    def __str__(self):
        return self.empid


class TaxDeclaration(models.Model):

    empid = models.CharField(max_length=50,  null=True)
    empname = models.TextField(blank=True, null=True)
    mobno = models.CharField(max_length=50, blank=True, null=True)
    emailid = models.EmailField(max_length=100, blank=True, null=True)
    pan = models.CharField(max_length=50, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)

    d_houserentstartdt = models.DateField(blank=True, null=True)
    d_rentpermonth = models.BigIntegerField(blank=True, null=True)
    d_landlordsname = models.CharField(max_length=50, blank=True, null=True)
    d_landlordspannum = models.CharField(max_length=50, blank=True, null=True)
    d_landlordscontact = models.CharField(max_length=30, blank=True, null=True)
    d_citytype = models.CharField(max_length=30, blank=True, null=True)
    d_landlordsaddress = models.CharField(max_length=100, blank=True, null=True)
    d_rentaddress = models.CharField(max_length=100, blank=True, null=True)
    d_pincode = models.BigIntegerField(blank=True, null=True)

    d_selfloan_dt = models.DateTimeField(blank=True, null=True, default=None)
    d_selfoccupiedloanint = models.BigIntegerField(blank=True, null=True)
    d_selflendername = models.CharField(max_length=200, blank=True, null=True)
    d_selflenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_selfotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_selfotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_letannuallettable = models.BigIntegerField(blank=True, null=True)
    d_letmunicipalprotax = models.BigIntegerField(blank=True, null=True)
    d_lethomeloaninterest = models.BigIntegerField(blank=True, null=True)
    d_letincomeloss = models.BigIntegerField(blank=True, null=True)
    d_letstanderedded = models.BigIntegerField(blank=True, null=True)
    d_letlendername = models.CharField(max_length=200, blank=True, null=True)
    d_letlenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_letotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_letotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_80eeloadsanctiondt = models.DateTimeField(blank=True, null=True)
    d_80eeloanammount = models.BigIntegerField(blank=True, null=True)
    d_80eepropertyvalue = models.BigIntegerField(blank=True, null=True)
    d_80eehomeloanint = models.BigIntegerField(blank=True, null=True)
    d_80eelendername = models.CharField(max_length=200, blank=True, null=True)
    d_80eelenderpannum = models.CharField(max_length=50, blank=True, null=True)
    d_80eeotherlendername = models.CharField(max_length=200, blank=True, null=True)
    d_80eeotherlenderpannum = models.CharField(max_length=50, blank=True, null=True)

    d_80eealoadsanctiondt = models.DateTimeField(blank=True, null=True)
    d_80eeahaveproperty = models.CharField(max_length=20, blank=True, null=True)
    d_80eeaprpertyvalue = models.BigIntegerField(blank=True, null=True)
    d_80eeaeligibility = models.CharField(max_length=20, blank=True, null=True)

    d_80ttaotherincome = models.BigIntegerField( blank=True, null=True)
    d_80ttasavinginterest = models.BigIntegerField( blank=True, null=True)

    d_80dselfinsurance = models.BigIntegerField(blank=True, null=True)
    d_80dnonseniorinsurance = models.BigIntegerField( blank=True, null=True)
    d_80dseniorinsurance = models.BigIntegerField(blank=True, null=True)
    d_80dpreventivecheckup = models.BigIntegerField(blank=True, null=True)
    
    d_80dillnesstype = models.CharField(max_length=100, blank=True, null=True)
    d_80ddbmedicalfield = models.CharField(max_length=100, blank=True, null=True)
    d_80ddbmedicaltreatment = models.BigIntegerField(blank=True, null=True)

    d_80eeducation_dt = models.DateTimeField(blank=True, null=True, default=None)
    d_80eeducationint = models.BigIntegerField(blank=True, null=True)

    d_80uselfdisable = models.BigIntegerField(blank=True, null=True)
    d_80dddependdisable = models.BigIntegerField(blank=True, null=True)

    d_80eebvehicltype = models.CharField(max_length=50, blank=True, null=True)
    d_80eebloansactiondt = models.DateTimeField(blank=True, null=True)
    d_80eebcarint = models.BigIntegerField( blank=True, null=True)

    d_80ccbselfcontrib = models.BigIntegerField(blank=True, null=True)
    d_80ccbprannum = models.BigIntegerField(blank=True, null=True)

    d_80clifeinsurance = models.BigIntegerField( blank=True, null=True)
    d_80c5yrtimedeposit = models.BigIntegerField(blank=True, null=True)
    d_80culip =  models.BigIntegerField(blank=True, null=True)
    d_80cnscsubscription = models.BigIntegerField(blank=True, null=True)
    d_80cnscint = models.BigIntegerField( blank=True, null=True)
    d_80cpublicpfund = models.BigIntegerField( blank=True, null=True)
    d_80chouseloan = models.BigIntegerField(blank=True, null=True)
    d_80ctuitionfee = models.BigIntegerField(blank=True, null=True)
    d_80cmutualfund = models.BigIntegerField( blank=True, null=True)
    d_80ctermdposite = models.BigIntegerField(blank=True, null=True)
    d_80csuksam = models.BigIntegerField(blank=True, null=True)

    d_prevsalary = models.BigIntegerField( blank=True, null=True)
    d_prevprofund = models.BigIntegerField( blank=True, null=True)
    d_prevprofessionaltax = models.BigIntegerField(blank=True, null=True)
    d_previncometax = models.BigIntegerField(blank=True, null=True)
    
    saveddate = models.DateTimeField(blank=True, null=True)
    
    sub1Date = models.DateTimeField(blank=True, null=True)
    itdInt80eeB = models.BigIntegerField( blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    Declaration_no = models.CharField(max_length=50, blank=True, null=True)
    Declaration_check = models.BooleanField(blank=True, null=True)

    TS0581 = models.DateTimeField(blank=True, null=True)
    TS058401S = models.DateTimeField(blank=True, null=True)
    TS058401L = models.DateTimeField(blank=True, null=True)
    TS058402 = models.DateTimeField(blank=True, null=True)
    TS0584 = models.DateTimeField(blank=True, null=True)
    TS0585 = models.DateTimeField(blank=True, null=True)
    TS0586 = models.DateTimeField(blank=True, null=True)
    TS0580 = models.DateTimeField(blank=True, null=True)
    FLG0580 = models.BooleanField(blank=True, null=True)
    FLG0581 = models.BooleanField(blank=True, null=True)
    FLG058401S = models.BooleanField(blank=True, null=True)
    FLG058401L = models.BooleanField(blank=True, null=True)
    FLG058402 = models.BooleanField(blank=True, null=True)
    FLG0584 = models.BooleanField(blank=True, null=True)
    FLG0585 = models.BooleanField(blank=True, null=True)
    FLG0586 = models.BooleanField(blank=True, null=True)
    TSSubmit = models.DateTimeField(blank=True, null=True)
    GENTS0580 = models.DateTimeField(blank=True, null=True)
    GENTS0581 = models.DateTimeField(blank=True, null=True)
    GENTS058401S = models.DateTimeField(blank=True, null=True)
    GENTS058401L = models.DateTimeField(blank=True, null=True)
    GENTS058402 = models.DateTimeField(blank=True, null=True)
    GENTS0585 = models.DateTimeField(blank=True, null=True)
    GENTS0586 = models.DateTimeField(blank=True, null=True)
    REGENTS0580 = models.DateTimeField(blank=True, null=True)
    REGENTS0581 = models.DateTimeField(blank=True, null=True)
    REGENTS058401S = models.DateTimeField(blank=True, null=True)
    REGENTS058401L = models.DateTimeField(blank=True, null=True)
    REGENTS058402 = models.DateTimeField(blank=True, null=True)
    REGENTS0585 = models.DateTimeField(blank=True, null=True)
    REGENTS0586 = models.DateTimeField(blank=True, null=True)
    loanDt80eeA = models.DateTimeField(blank=True, null=True)
    propertyVal80eeA = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)

    itd21 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    itd23 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    itd80ccg = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    sub1Complete = models.BooleanField(blank=True, null=True)
    empDeclaration = models.BooleanField(blank=True, null=True)
    itd80CCD1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    rd80ddb = models.CharField(max_length=50, blank=True, null=True)
    itdInt80ee = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    rdRentFullYear = models.CharField(max_length=10, blank=True, null=True)
    rdChangeRent = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.empid
    

class TaxRegime(models.Model):

    empid = models.CharField(max_length=50,  null=True)
    Regime = models.CharField(max_length=50, blank=True, null=True, default='New')
    TSSave = models.DateTimeField(blank=True, null=True)
    TSSubmit = models.DateTimeField(blank=True, null=True)
    Claimno = models.CharField(max_length=50, blank=True, null=True)
    FLG588 = models.BooleanField(blank=True, null=True)
    GENTS = models.DateTimeField(blank=True, null=True)
    Resend = models.BooleanField(blank=True, null=True)
    RE_GEN_TS = models.DateTimeField(blank=True, null=True)
    Change = models.BooleanField(blank=True, null=True)

    def __str__(self):
        return self.empid


class LoanlendersDetails(models.Model):
    LoanLenderName = models.CharField(max_length=350, blank=True, null=True )
    LoanLenderPan = models.CharField(max_length=20, blank=True, null=True)


class illnesstypes(models.Model):
    illnessname = models.CharField(max_length=100, null=True, blank=True)


class itprooffiles(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    emppan = models.CharField(max_length=50,  null=True)
    section = models.CharField(max_length=50,  null=True)
    filename = models.CharField(max_length=50,  null=True)
    file_path = models.CharField(max_length=100,  null=True)
    file_status = models.CharField(max_length=50,  null=True)
    uploaddt = models.DateTimeField()


class it_proof_basic(models.Model):
    empid = models.CharField(max_length=20)
    userid = models.CharField(max_length=20, unique=True)
    empname = models.TextField(blank=True, null=True)
    mobno = models.CharField(max_length=50, blank=True, null=True)
    emailid = models.EmailField(max_length=60, blank=True, null=True)
    pan = models.CharField(max_length=50, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    doj = models.DateField(blank=True, null=True)
    fathername = models.CharField(max_length=50, null=True)
    isValidPAN = models.BooleanField(null=True)

    saveddate = models.DateTimeField(null=True)
    

    gender = models.CharField(max_length=15, null=True)
    CompanyName = models.CharField(max_length=50, null=True)
    status = models.CharField(max_length=50, null=True)
    
    Place = models.CharField(max_length=30, null=True)
    confirm_check = models.BooleanField(null=True, blank=True)

    ver_level_1 = models.BooleanField(null=True, blank=True, default=None)
    ver_level_2 = models.BooleanField(null=True, blank=True, default=None)

    ispan_decl = models.CharField(max_length=50, null=True)
    remarks = models.TextField(null=True)
    operator = models.CharField(max_length=50, null=True)
    operator_2 = models.CharField(max_length=50, null=True)
    operator_3 = models.CharField(max_length=50, null=True)
    operatorL3 = models.CharField(max_length=50, null=True)
    
    
    submit_DT = models.DateTimeField(null=True) # saved at emp save
    sub2Date = models.DateTimeField(null=True) # resub1 in itproof 
    sub3Date = models.DateTimeField(null=True) # resub2 in itproof 
    
    ver1Date = models.DateTimeField(null=True, default=None) # saved in maker    
    verL2Date = models.DateTimeField(null=True, default=None) # saved in checker + 6days resub1

    ver2Date = models.DateTimeField(null=True, default=None) # resub1 in checker + 6days resub2
    ver3Date = models.DateTimeField(null=True, default=None) # resub2 in checker
    
    

    exFlag2 = models.BooleanField(null=True) 
    exFlag3 = models.BooleanField(null=True)
    empDeclaration = models.BooleanField(null=True)
    rdIsMailCorrect = models.BooleanField(null=True)  
    sent = models.BooleanField(null=True)

    Admin_TS = models.DateTimeField(null=True)
    Admin_FLG = models.BooleanField(null=True)
    Admin_op = models.CharField(max_length=50, null=True)
    FLG0580 = models.BooleanField(null=True)
    FLG0581 = models.BooleanField(null=True)
    FLG0581H2 = models.BooleanField(null=True)
    FLG0581H3 = models.BooleanField(null=True)
    FLG0581H4 = models.BooleanField(null=True)
    FLG0581H5 = models.BooleanField(null=True)
    FLG058401S = models.BooleanField(null=True)
    FLG058401L = models.BooleanField(null=True)
    FLG058402 = models.BooleanField(null=True)
    FLG0585 = models.BooleanField(null=True)
    FLG0586 = models.BooleanField(null=True)
    GENTS0580 = models.DateTimeField(null=True)
    GENTS0581 = models.DateTimeField(null=True)
    GENTS0581H2 = models.DateTimeField(null=True)
    GENTS0581H3 = models.DateTimeField(null=True)
    GENTS0581H4 = models.DateTimeField(null=True)
    GENTS0581H5 = models.DateTimeField(null=True)
    GENTS058401S = models.DateTimeField(null=True)
    GENTS058401L = models.DateTimeField(null=True)
    GENTS058402 = models.DateTimeField(null=True)
    GENTS0585 = models.DateTimeField(null=True)
    GENTS0586 = models.DateTimeField(null=True)
    FLG0581H01_2 = models.BooleanField(null=True)
    FLG0581H02_3 = models.BooleanField(null=True)
    FLG0581H03_4 = models.BooleanField(null=True)
    FLG0581H04_5 = models.BooleanField(null=True)
    FLG0581H05_6 = models.BooleanField(null=True)
    GENTS0581H01_2 = models.DateTimeField(null=True)
    GENTS0581H02_3 = models.DateTimeField(null=True)
    GENTS0581H03_4 = models.DateTimeField(null=True)
    GENTS0581H04_5 = models.DateTimeField(null=True)
    GENTS0581H05_6 = models.DateTimeField(null=True)

    

    current_page = models.BigIntegerField(null=True)

    custom_remark = models.CharField(max_length=250, default=None, null=True)

    def __str__(self):
        return self.empid



class it_proof_hra(models.Model):
    empid = models.CharField(max_length=20)

    claimingHRA = models.CharField(max_length=10, blank=True, null=True)
    changeHRA = models.CharField(max_length=10, blank=True, null=True)

    mode_of_pay = models.CharField(max_length=20, blank=True, null=True)

    LandLordPan = models.CharField(max_length=50, null=True)
    itd1stdt = models.DateField(blank=True, null=True)
    itd1enddt = models.DateField(blank=True, null=True)
    itd1 = models.BigIntegerField(blank=True, null=True)  
    pincode1 = models.IntegerField(null=True)   
    city1 = models.CharField(max_length=50, blank=True, null=True)
    landlordName = models.CharField(max_length=50, null=True)
    LandlordContact = models.CharField(max_length=30, null=True)
    LandlordAddress = models.CharField(max_length=250, null=True)
    rentedAdd1 = models.CharField(max_length=250, null=True)

    LandlordPan2 = models.CharField(max_length=50, null=True)
    itd2stdt = models.DateField(blank=True, null=True)
    itd2enddt = models.DateField(blank=True, null=True)
    itd2 = models.BigIntegerField(blank=True, null=True) 
    pincode2 = models.IntegerField(null=True)
    city2 = models.CharField(max_length=50, blank=True, null=True)    
    LandlordName2 = models.CharField(max_length=50, null=True)
    LandlordContact2 = models.CharField(max_length=50, null=True)
    LandlordAdd2 = models.CharField(max_length=250, null=True)
    rentedAdd2 = models.CharField(max_length=250, null=True) 


    LandlordPan3 = models.CharField(max_length=50, null=True)
    itd3stdt = models.DateField(null=True)
    itd3enddt = models.DateField(null=True)
    itd3 = models.BigIntegerField(null=True)
    pincode3 = models.IntegerField(null=True)
    city3 = models.CharField(max_length=50, null=True)
    LandlordName3 = models.CharField(max_length=50, null=True)
    LandlordContact3 = models.CharField(max_length=50, null=True)
    LandlordAdd3 = models.CharField(max_length=250, null=True)
    rentedAdd3 = models.CharField(max_length=250, null=True)

    LandlordPan4 = models.CharField(max_length=50, null=True)
    itd4stdt = models.DateField(null=True)
    itd4enddt = models.DateField(null=True)
    itd4 = models.BigIntegerField(null=True)
    pincode4 = models.IntegerField(null=True)
    city4 = models.CharField(max_length=50, null=True)
    LandlordName4 = models.CharField(max_length=50, null=True)
    LandlordContact4 = models.CharField(max_length=50, null=True)
    LandlordAdd4 = models.CharField(max_length=250, null=True)
    rentedAdd4 = models.CharField(max_length=250, null=True)

    LandlordPan5 = models.CharField(max_length=50, null=True)
    itd5stdt = models.DateField(null=True)
    itd5enddt = models.DateField(null=True)
    itd5 = models.BigIntegerField(null=True)
    pincode5 = models.IntegerField(null=True)
    city5 = models.CharField(max_length=50, null=True)
    LandlordName5 = models.CharField(max_length=50, null=True)
    LandlordContact5 = models.CharField(max_length=50, null=True)
    LandlordAdd5 = models.CharField(max_length=250, null=True)
    rentedAdd5 = models.CharField(max_length=250, null=True)

    ita1 = models.BigIntegerField(null=True, default=None)
    ita2 = models.BigIntegerField(null=True, default=None)
    ita3 = models.BigIntegerField(null=True, default=None)
    ita4 = models.BigIntegerField(null=True, default=None)
    ita5 = models.BigIntegerField(null=True, default=None)

    ita1_2 = models.BigIntegerField(null=True, default=None)
    ita2_2 = models.BigIntegerField(null=True, default=None)
    ita3_2 = models.BigIntegerField(null=True, default=None)
    ita4_2 = models.BigIntegerField(null=True, default=None)
    ita5_2 = models.BigIntegerField(null=True, default=None)

    ita1_3 = models.BigIntegerField(null=True, default=None)
    ita2_3 = models.BigIntegerField(null=True, default=None)
    ita3_3 = models.BigIntegerField(null=True, default=None)
    ita4_3 = models.BigIntegerField(null=True, default=None)
    ita5_3 = models.BigIntegerField(null=True, default=None)

    ita1stdt = models.DateField(null=True, default=None)
    ita1enddt = models.DateField(null=True, default=None)
    a_city1 = models.CharField(max_length=50, null=True)


    ita2stdt = models.DateField(null=True, default=None)
    ita2enddt = models.DateField(null=True, default=None)
    a_city2 = models.CharField(max_length=50, null=True)

    
    ita3stdt = models.DateField(null=True, default=None)
    ita3enddt = models.DateField(null=True, default=None)
    a_city3 = models.CharField(max_length=50, null=True)

    
    ita4stdt = models.DateField(null=True, default=None)
    ita4enddt = models.DateField(null=True, default=None)
    a_city4 = models.CharField(max_length=50, null=True)

   
    ita5stdt = models.DateField(null=True, default=None)
    ita5enddt = models.DateField(null=True, default=None)
    a_city5 = models.CharField(max_length=50, null=True)
        
    
    hra_remark_1 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_2 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_3 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_4 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_5 =  models.CharField(max_length=250, default=None, null=True)

    hra_remark_1_2 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_2_2 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_3_2 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_4_2 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_5_2 =  models.CharField(max_length=250, default=None, null=True)

    hra_remark_1_3 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_2_3 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_3_3 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_4_3 =  models.CharField(max_length=250, default=None, null=True)
    hra_remark_5_3 =  models.CharField(max_length=250, default=None, null=True)

class it_proof_income_loss(models.Model):
    empid = models.CharField(max_length=20)
   
    #Self Occupied Property
    self_date = models.DateField(null=True, default=None)
    selfOccupiedHouseProperty=models.BigIntegerField(null=True)
    selfHomeLoanLenderName=models.CharField(max_length=100, null=True)
    selfHomeLoanLenderPAN=models.CharField(max_length=50, null=True)
    otherselfHomeLoanLenderName=models.CharField(max_length=100, null=True)
    otherselfHomeLoanLenderPAN=models.CharField(max_length=50, null=True)

    #Let Out Property
    annualLettableValue=models.BigIntegerField(null=True)
    municipalPropertyTax=models.BigIntegerField(null=True)
    homeLoanInterest=models.BigIntegerField(null=True)
    incomeLossOnHouseProperty=models.BigIntegerField(null=True)
    standardDeduction=models.BigIntegerField(null=True)
    loanLenderName=models.CharField(max_length=100, null=True)
    loanLenderPAN=models.CharField(max_length=50, null=True)
    otherloanLenderName=models.CharField(max_length=100, null=True)
    otherloanLenderPAN=models.CharField(max_length=50, null=True)

    #80 EE
    loan_sanctioned_date=models.DateField(null=True)
    loan_amount=models.BigIntegerField(null=True)
    property_value=models.BigIntegerField(null=True)
    home_loan=models.BigIntegerField(null=True)
    loan_lender=models.CharField(max_length=100, null=True)
    lender_pan=models.CharField(max_length=50, null=True)
    otherloan_lender=models.CharField(max_length=100, null=True)
    otherlender_pan=models.CharField(max_length=50, null=True)

    #80 EEA
    loan_sanctioned_date_ee=models.DateField(null=True)
    op80eea_other_property=models.BooleanField(null=True)
    op80eea_other_property_new = models.CharField(max_length=10, null=True, default=None)
    property_value_other=models.BigIntegerField(null=True)
    op80eea=models.BooleanField(null=True)
    
    #other Income
    other_income_oi=models.BigIntegerField(null=True)

    #80 TTA
    interest_80tta=models.BigIntegerField(null=True)


    #self-occupied
    is_house_self =models.CharField(max_length=50, null=True)
    
    sole_join_owner_self=models.CharField(max_length=50, null=True)
    name_joint_owner_slef=models.CharField(max_length=50, null=True)
    relationship_self=models.CharField(max_length=50, null=True)
    extent_income_tax_self=models.BigIntegerField(null=True)
    principal_loan_tax_self=models.BigIntegerField(null=True)
    property_address_self=models.CharField(max_length=350, null=True)
    barrow_date_self=models.DateField(null=True)
    possession_date_self=models.DateField(null=True)


    sole_join_owner_let=models.CharField(max_length=50, null=True)
    name_joint_owner_let=models.CharField(max_length=50, null=True)
    relationship_let=models.CharField(max_length=50, null=True)
    extent_income_tax_let=models.BigIntegerField(null=True)
    principal_loan_tax_let=models.BigIntegerField(null=True)
    property_address_let=models.CharField(max_length=350, null=True)
    barrow_date_let=models.DateField(null=True)
    possession_date_let=models.DateField(null=True)

    hra_hl_startdt = models.DateField(null=True)
    hra_hl_enddt = models.DateField(null=True)

    other_place = models.CharField(max_length=50, null=True, default=None)
    tta80_place = models.CharField(max_length=50, null=True, default=None)
    place_80ee = models.CharField(max_length=50, null=True, default=None)    
    place_80eea = models.CharField(max_length=50, null=True, default=None)

    loc_80ee = models.CharField(max_length=50, null=True, default=None)
    loc_80eea = models.CharField(max_length=50, null=True, default=None)
    hl_80eea=models.BigIntegerField(null=True, default=None)

    
    
    #allowed
    allowed_self = models.BigIntegerField(null=True, default=None)

    allowed_self_2 = models.BigIntegerField(null=True, default=None)
    allowed_self_3 = models.BigIntegerField(null=True, default=None)

    allowed_annualLettableValue = models.BigIntegerField(null=True, default=None)
    allowed_municipalPropertyTax = models.BigIntegerField(null=True, default=None)
    allowed_homeLoanInterest = models.BigIntegerField(null=True, default=None)
    allowed_incomeLossOnHouseProperty = models.BigIntegerField(null=True, default=None)
    allowed_standardDeduction = models.BigIntegerField(null=True, default=None)

    allowed_annualLettableValue_2 = models.BigIntegerField(null=True, default=None)
    allowed_municipalPropertyTax_2 = models.BigIntegerField(null=True, default=None)
    allowed_homeLoanInterest_2= models.BigIntegerField(null=True, default=None)
    allowed_incomeLossOnHouseProperty_2 = models.BigIntegerField(null=True, default=None)
    allowed_standardDeduction_2 = models.BigIntegerField(null=True, default=None)

    allowed_annualLettableValue_3 = models.BigIntegerField(null=True, default=None)
    allowed_municipalPropertyTax_3 = models.BigIntegerField(null=True, default=None)
    allowed_homeLoanInterest_3 = models.BigIntegerField(null=True, default=None)
    allowed_incomeLossOnHouseProperty_3 = models.BigIntegerField(null=True, default=None)
    allowed_standardDeduction_3 = models.BigIntegerField(null=True, default=None)

    
    allowed_loan_amount = models.BigIntegerField(null=True, default=None)
    allowed_property_value = models.BigIntegerField(null=True, default=None)
    allowed_home_loan = models.BigIntegerField(null=True, default=None)

    allowed_loan_amount_2 = models.BigIntegerField(null=True, default=None)
    allowed_property_value_2 = models.BigIntegerField(null=True, default=None)
    allowed_home_loan_2 = models.BigIntegerField(null=True, default=None)

    allowed_loan_amount_3 = models.BigIntegerField(null=True, default=None)
    allowed_property_value_3 = models.BigIntegerField(null=True, default=None)
    allowed_home_loan_3 = models.BigIntegerField(null=True, default=None)

    
    allowed_property_value_other = models.BigIntegerField(null=True, default=None)
    allowed_property_value_other_2 = models.BigIntegerField(null=True, default=None)
    allowed_property_value_other_3 = models.BigIntegerField(null=True, default=None)

    allowed_other_income_oi = models.BigIntegerField(null=True, default=None)
    allowed_interest_80tta = models.BigIntegerField(null=True, default=None)

    allowed_other_income_oi_2 = models.BigIntegerField(null=True, default=None)
    allowed_interest_80tta_2 = models.BigIntegerField(null=True, default=None)

    allowed_other_income_oi_3 = models.BigIntegerField(null=True, default=None)
    allowed_interest_80tta_3 = models.BigIntegerField(null=True, default=None)

    #remarks
    self_remark = models.CharField(max_length=250, null=True, default=None)
    allowed_annualLettableValue_remark =  models.CharField(max_length=250, null=True, default=None)
    allowed_municipalPropertyTax_remark =  models.CharField(max_length=250, null=True, default=None)
    allowed_homeLoanInterest_remark =  models.CharField(max_length=250, null=True, default=None)
    allowed_incomeLossOnHouseProperty_remark =  models.CharField(max_length=250, null=True, default=None)
    allowed_standardDeduction_remark =  models.CharField(max_length=250, null=True, default=None)

    self_remark_2 = models.CharField(max_length=250, null=True, default=None)
    allowed_annualLettableValue_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    allowed_municipalPropertyTax_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    allowed_homeLoanInterest_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    allowed_incomeLossOnHouseProperty_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    allowed_standardDeduction_remark_2 =  models.CharField(max_length=250, null=True, default=None)

    self_remark_3 = models.CharField(max_length=250, null=True, default=None)
    allowed_annualLettableValue_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    allowed_municipalPropertyTax_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    allowed_homeLoanInterest_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    allowed_incomeLossOnHouseProperty_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    allowed_standardDeduction_remark_3 =  models.CharField(max_length=250, null=True, default=None)


    loan_amount_remark =  models.CharField(max_length=250, null=True, default=None)
    property_value_remark =  models.CharField(max_length=250, null=True, default=None)
    home_loan_remark =  models.CharField(max_length=250, null=True, default=None)
    
    property_value_other_remark =  models.CharField(max_length=250, null=True, default=None)

    other_income_oi_remark =  models.CharField(max_length=250, null=True, default=None)
    interest_80tta_remark = models.CharField(max_length=250, null=True, default=None)

    loan_amount_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    property_value_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    home_loan_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    
    property_value_other_remark_2 =  models.CharField(max_length=250, null=True, default=None)

    other_income_oi_remark_2 =  models.CharField(max_length=250, null=True, default=None)
    interest_80tta_remark_2 = models.CharField(max_length=250, null=True, default=None)

    loan_amount_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    property_value_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    home_loan_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    
    property_value_other_remark_3 =  models.CharField(max_length=250, null=True, default=None)

    other_income_oi_remark_3 =  models.CharField(max_length=250, null=True, default=None)
    interest_80tta_remark_3 = models.CharField(max_length=250, null=True, default=None)

class it_proof_80_other(models.Model):
    empid = models.CharField(max_length=20)
    #Medical Insurance
    medical_insurance_self_mip=models.BigIntegerField(null=True)
    medical_insurance_parents_mip=models.BigIntegerField(null=True)
    medical_insurance_Senior_Citizen=models.BigIntegerField(null=True)
    preventive_health_checkup_mip=models.BigIntegerField(null=True)

    #80 DDB
    selected_illness=models.CharField(max_length=100, null=True)
    citizenship_status=models.CharField(max_length=100, null=True)
    treatment_value=models.BigIntegerField(null=True)

    #80 E
    interest_education=models.BigIntegerField(null=True)

    #80 U/ DD
    paymentDependentDisability=models.CharField(null=True, max_length=100) 
    paymentSelfDisability=models.CharField(null=True, max_length=100)

    #80 EEB
    loan_sanctioned_date_80eeb=models.DateField(null=True)
    vehicle_loan_80eeb=models.BigIntegerField(null=True)
    loan_lender_80eeb=models.CharField(null=True, max_length=100)
    lender_pan_80eeb=models.CharField(null=True, max_length=100)
    other80eebLender=models.CharField(null=True, max_length=100)
    other80eebPAN=models.CharField(null=True, max_length=100)

    #80ccd(1B)
    section80ccdcontribution=models.CharField(max_length=100, null=True)
    nps_80ccd1b=models.BigIntegerField(null=True)
    prannumber=models.BigIntegerField(null=True)

    #declarations fields

    mip_for = models.CharField(null=True, max_length=30, default=None)
    critical_illness_for = models.CharField(null=True, max_length=30, default=None)
    dependent_dis_for = models.CharField(null=True, max_length=30, default=None)
    education_loan_for = models.CharField(null=True, max_length=30, default=None)

    ded80_place = models.CharField(max_length=50, null=True, default=None)
    veh_reg_num = models.CharField(max_length=20, null=True, default=None)
    eeb80_place = models.CharField(max_length=50, null=True, default=None)
    
    #allowed
    allowed_medical_insurance = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_nsn = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_sn = models.BigIntegerField(null=True, default=None)
    allowed_health_checkup = models.BigIntegerField(null=True, default=None)

    allowed_medical_insurance_2 = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_nsn_2 = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_sn_2 = models.BigIntegerField(null=True, default=None)
    allowed_health_checkup_2 = models.BigIntegerField(null=True, default=None)

    allowed_medical_insurance_3 = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_nsn_3 = models.BigIntegerField(null=True, default=None)
    allowed_parents_mip_sn_3 = models.BigIntegerField(null=True, default=None)
    allowed_health_checkup_3 = models.BigIntegerField(null=True, default=None)

    allowed_treatment_value = models.BigIntegerField(null=True, default=None)
    allowed_interest_education = models.BigIntegerField(null=True, default=None)

    allowed_treatment_value_2 = models.BigIntegerField(null=True, default=None)
    allowed_interest_education_2 = models.BigIntegerField(null=True, default=None)

    allowed_treatment_value_3 = models.BigIntegerField(null=True, default=None)
    allowed_interest_education_3 = models.BigIntegerField(null=True, default=None)

    allowed_Dependent_dis = models.BigIntegerField(null=True, default=None)
    allowed_self_dis = models.BigIntegerField(null=True, default=None)

    allowed_Dependent_dis_2 = models.BigIntegerField(null=True, default=None)
    allowed_self_dis_2 = models.BigIntegerField(null=True, default=None)

    allowed_Dependent_dis_3 = models.BigIntegerField(null=True, default=None)
    allowed_self_dis_3 = models.BigIntegerField(null=True, default=None)

    allowed_vehicle_value = models.BigIntegerField(null=True, default=None)
    allowed_nps_80ccd1b = models.BigIntegerField(null=True, default=None)

    allowed_vehicle_value_2 = models.BigIntegerField(null=True, default=None)
    allowed_nps_80ccd1b_2 = models.BigIntegerField(null=True, default=None)

    allowed_vehicle_value_3 = models.BigIntegerField(null=True, default=None)
    allowed_nps_80ccd1b_3 = models.BigIntegerField(null=True, default=None)


    #remarks
    medical_insurance_remark = models.CharField(max_length=250, null=True, default=None)
    parents_mip_nsn_remark = models.CharField(max_length=250, null=True, default=None)
    parents_mip_sn_remark = models.CharField(max_length=250, null=True, default=None)
    health_checkup_remark = models.CharField(max_length=250, null=True, default=None)

    medical_insurance_remark_2 = models.CharField(max_length=250, null=True, default=None)
    parents_mip_nsn_remark_2 = models.CharField(max_length=250, null=True, default=None)
    parents_mip_sn_remark_2 = models.CharField(max_length=250, null=True, default=None)
    health_checkup_remark_2 = models.CharField(max_length=250, null=True, default=None)

    medical_insurance_remark_3 = models.CharField(max_length=250, null=True, default=None)
    parents_mip_nsn_remark_3 = models.CharField(max_length=250, null=True, default=None)
    parents_mip_sn_remark_3 = models.CharField(max_length=250, null=True, default=None)
    health_checkup_remark_3 = models.CharField(max_length=250, null=True, default=None)


    treatment_value_remark = models.CharField(max_length=250, null=True, default=None)
    interest_education_remark = models.CharField(max_length=250, null=True, default=None)

    treatment_value_remark_2 = models.CharField(max_length=250, null=True, default=None)
    interest_education_remark_2 = models.CharField(max_length=250, null=True, default=None)

    treatment_value_remark_3 = models.CharField(max_length=250, null=True, default=None)
    interest_education_remark_3 = models.CharField(max_length=250, null=True, default=None)

    allowed_Dependent_remark = models.CharField(max_length=250, null=True, default=None)
    allowed_self_remark = models.CharField(max_length=250, null=True, default=None)

    allowed_Dependent_remark_2 = models.CharField(max_length=250, null=True, default=None)
    allowed_self_remark_2 = models.CharField(max_length=250, null=True, default=None)

    allowed_Dependent_remark_3 = models.CharField(max_length=250, null=True, default=None)
    allowed_self_remark_3 = models.CharField(max_length=250, null=True, default=None)


    vehicle_value_remark = models.CharField(max_length=250, null=True, default=None)
    nps_80ccd1b_remark = models.CharField(max_length=250, null=True, default=None)

    vehicle_value_remark_2 = models.CharField(max_length=250, null=True, default=None)
    nps_80ccd1b_remark_2 = models.CharField(max_length=250, null=True, default=None)

    vehicle_value_remark_3 = models.CharField(max_length=250, null=True, default=None)
    nps_80ccd1b_remark_3 = models.CharField(max_length=250, null=True, default=None)

class it_proof_80C_Contribution(models.Model):
    empid = models.CharField(max_length=20)
    paymentLifeInsurance=models.BigIntegerField(null=True)
    timeDeposit=models.BigIntegerField(null=True)
    ulipContribution=models.BigIntegerField(null=True)
    nscSubscription=models.BigIntegerField(null=True)
    nscInterest=models.BigIntegerField(null=True)
    ppfContribution=models.BigIntegerField(null=True)
    houseLoan=models.BigIntegerField(null=True)
    tuitionFee=models.BigIntegerField(null=True)
    mutualFundSubscription=models.BigIntegerField(null=True)
    termDeposits=models.BigIntegerField(null=True)
    pensionContribution=models.BigIntegerField(null=True)
    sukanyaSamriddhi=models.BigIntegerField(null=True)


    
    lic_for = models.CharField(max_length=30, null=True, default=None)
    ppf_for = models.CharField(max_length=30, null=True, default=None)
    c80_place = models.CharField(max_length=50, null=True, default=None)


    #allowed
    allowed_paymentLifeInsurance = models.BigIntegerField(null=True)
    allowed_timeDeposit = models.BigIntegerField(null=True)
    allowed_ulipContribution = models.BigIntegerField(null=True)
    allowed_nscSubscription = models.BigIntegerField(null=True)
    allowed_nscInterest = models.BigIntegerField(null=True)
    allowed_ppfContribution = models.BigIntegerField(null=True)
    allowed_houseLoan = models.BigIntegerField(null=True)
    allowed_tuitionFee = models.BigIntegerField(null=True)
    allowed_mutualFundSubscription = models.BigIntegerField(null=True)
    allowed_termDeposits = models.BigIntegerField(null=True)
    allowed_pensionContribution= models.BigIntegerField(null=True)
    allowed_sukanyaSamriddhi = models.BigIntegerField(null=True)

    allowed_paymentLifeInsurance_2 = models.BigIntegerField(null=True)
    allowed_timeDeposit_2 = models.BigIntegerField(null=True)
    allowed_ulipContribution_2 = models.BigIntegerField(null=True)
    allowed_nscSubscription_2 = models.BigIntegerField(null=True)
    allowed_nscInterest_2 = models.BigIntegerField(null=True)
    allowed_ppfContribution_2 = models.BigIntegerField(null=True)
    allowed_houseLoan_2 = models.BigIntegerField(null=True)
    allowed_tuitionFee_2 = models.BigIntegerField(null=True)
    allowed_mutualFundSubscription_2 = models.BigIntegerField(null=True)
    allowed_termDeposits_2 = models.BigIntegerField(null=True)
    allowed_pensionContribution_2= models.BigIntegerField(null=True)
    allowed_sukanyaSamriddhi_2 = models.BigIntegerField(null=True)

    allowed_paymentLifeInsurance_3 = models.BigIntegerField(null=True)
    allowed_timeDeposit_3 = models.BigIntegerField(null=True)
    allowed_ulipContribution_3 = models.BigIntegerField(null=True)
    allowed_nscSubscription_3 = models.BigIntegerField(null=True)
    allowed_nscInterest_3 = models.BigIntegerField(null=True)
    allowed_ppfContribution_3 = models.BigIntegerField(null=True)
    allowed_houseLoan_3 = models.BigIntegerField(null=True)
    allowed_tuitionFee_3 = models.BigIntegerField(null=True)
    allowed_mutualFundSubscription_3 = models.BigIntegerField(null=True)
    allowed_termDeposits_3 = models.BigIntegerField(null=True)
    allowed_pensionContribution_3= models.BigIntegerField(null=True)
    allowed_sukanyaSamriddhi_3 = models.BigIntegerField(null=True)

    #remarks
    paymentLifeInsurance_remark = models.CharField(max_length=250,null=True)
    timeDeposit_remark = models.CharField(max_length=250,null=True)
    ulipContribution_remark = models.CharField(max_length=250,null=True)
    nscSubscription_remark = models.CharField(max_length=250,null=True)
    nscInterest_remark = models.CharField(max_length=250,null=True)
    ppfContribution_remark = models.CharField(max_length=250,null=True)
    houseLoan_remark = models.CharField(max_length=250,null=True)
    tuitionFee_remark = models.CharField(max_length=250,null=True)
    mutualFundSubscription_remark= models.CharField(max_length=250,null=True)
    termDeposits_remark = models.CharField(max_length=250,null=True)
    pensionContribution_remark = models.CharField(max_length=250,null=True)
    sukanyaSamriddhi_remark = models.CharField(max_length=250,null=True)

    paymentLifeInsurance_remark_2 = models.CharField(max_length=250,null=True)
    timeDeposit_remark_2 = models.CharField(max_length=250,null=True)
    ulipContribution_remark_2 = models.CharField(max_length=250,null=True)
    nscSubscription_remark_2 = models.CharField(max_length=250,null=True)
    nscInterest_remark_2 = models.CharField(max_length=250,null=True)
    ppfContribution_remark_2 = models.CharField(max_length=250,null=True)
    houseLoan_remark_2 = models.CharField(max_length=250,null=True)
    tuitionFee_remark_2 = models.CharField(max_length=250,null=True)
    mutualFundSubscription_remark_2= models.CharField(max_length=250,null=True)
    termDeposits_remark_2 = models.CharField(max_length=250,null=True)
    pensionContribution_remark_2 = models.CharField(max_length=250,null=True)
    sukanyaSamriddhi_remark_2 = models.CharField(max_length=250,null=True)

    paymentLifeInsurance_remark_3 = models.CharField(max_length=250,null=True)
    timeDeposit_remark_3 = models.CharField(max_length=250,null=True)
    ulipContribution_remark_3 = models.CharField(max_length=250,null=True)
    nscSubscription_remark_3 = models.CharField(max_length=250,null=True)
    nscInterest_remark_3 = models.CharField(max_length=250,null=True)
    ppfContribution_remark_3 = models.CharField(max_length=250,null=True)
    houseLoan_remark_3 = models.CharField(max_length=250,null=True)
    tuitionFee_remark_3 = models.CharField(max_length=250,null=True)
    mutualFundSubscription_remark_3= models.CharField(max_length=250,null=True)
    termDeposits_remark_3 = models.CharField(max_length=250,null=True)
    pensionContribution_remark_3 = models.CharField(max_length=250,null=True)
    sukanyaSamriddhi_remark_3 = models.CharField(max_length=250,null=True)

class it_proof_previousemp(models.Model):
    empid = models.CharField(max_length=20)
    salary_previousemp = models.BigIntegerField(null=True)
    provident_fund = models.BigIntegerField(null=True)
    professional_tax = models.BigIntegerField(null=True)
    income_tax = models.BigIntegerField(null=True) 

    #allowed
    allowed_salary_previousemp = models.BigIntegerField(null=True)
    allowed_provident_fund = models.BigIntegerField(null=True)
    allowed_professional_tax = models.BigIntegerField(null=True)
    allowed_income_tax = models.BigIntegerField(null=True)

    allowed_salary_previousemp_2 = models.BigIntegerField(null=True)
    allowed_provident_fund_2 = models.BigIntegerField(null=True)
    allowed_professional_tax_2 = models.BigIntegerField(null=True)
    allowed_income_tax_2 = models.BigIntegerField(null=True)

    allowed_salary_previousemp_3 = models.BigIntegerField(null=True)
    allowed_provident_fund_3 = models.BigIntegerField(null=True)
    allowed_professional_tax_3 = models.BigIntegerField(null=True)
    allowed_income_tax_3 = models.BigIntegerField(null=True)


    #remarks
    salary_previousemp_remark = models.CharField(max_length=250,null=True)
    provident_fund_remark = models.CharField(max_length=250,null=True)
    professional_tax_remark = models.CharField(max_length=250,null=True)
    income_tax_remark = models.CharField(max_length=250,null=True)

    salary_previousemp_remark_2 = models.CharField(max_length=250,null=True)
    provident_fund_remark_2 = models.CharField(max_length=250,null=True)
    professional_tax_remark_2 = models.CharField(max_length=250,null=True)
    income_tax_remark_2 = models.CharField(max_length=250,null=True)
 
    salary_previousemp_remark_3 = models.CharField(max_length=250,null=True)
    provident_fund_remark_3 = models.CharField(max_length=250,null=True)
    professional_tax_remark_3 = models.CharField(max_length=250,null=True)
    income_tax_remark_3 = models.CharField(max_length=250,null=True)

class declaration_files(models.Model):
    empid = models.CharField(max_length=50,  null=True)  
    section = models.CharField(max_length=50,  null=True)     
    filename = models.CharField(max_length=50,  null=True)
    file_path = models.CharField(max_length=100,  null=True)    
    uploaddt = models.DateTimeField()


class fbp_claim_file(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    section = models.CharField(max_length=50,  null=True)
    filename = models.CharField(max_length=50,  null=True)
    file_path = models.CharField(max_length=100,  null=True)    
    uploaddt = models.DateTimeField()
    reciept_no = models.CharField(max_length=50,  null=True, default = None)
    ClaimNo = models.CharField(max_length=50, null=True, default=None)
    
    save_number = models.CharField(max_length=50, null=True, default=None)


class fbp_dec_data(models.Model):
    empid = models.CharField(max_length=50,  null=True)

    save_number = models.CharField(max_length=50, null=True, default=None)

    # road
    road_check_1 = models.CharField(max_length=15,  null=True)
    road_check_2 = models.CharField(max_length=15,  null=True)
    road_check_3 = models.CharField(max_length=15,  null=True)

    # lta
    st_point = models.CharField(max_length=15,  null=True)
    end_point = models.CharField(max_length=15,  null=True)
    tra_mode = models.CharField(max_length=15,  null=True)
    tot_fare = models.BigIntegerField(blank=True, null=True)  

    st_dt = models.DateField(blank=True, null=True)
    end_dt = models.DateField(blank=True, null=True)

    fm_1 = models.CharField(max_length=25,  null=True)
    fm_2 = models.CharField(max_length=25,  null=True)
    fm_3 = models.CharField(max_length=25,  null=True)
    fm_4 = models.CharField(max_length=25,  null=True)
    fm_5 = models.CharField(max_length=25,  null=True)
    fm_6 = models.CharField(max_length=25,  null=True)
    fm_7 = models.CharField(max_length=25,  null=True)
    fm_8 = models.CharField(max_length=25,  null=True)

    rel_1 = models.CharField(max_length=25,  null=True)
    rel_2 = models.CharField(max_length=25,  null=True)
    rel_3 = models.CharField(max_length=25,  null=True)
    rel_4 = models.CharField(max_length=25,  null=True)
    rel_5 = models.CharField(max_length=25,  null=True)
    rel_6 = models.CharField(max_length=25,  null=True)
    rel_7 = models.CharField(max_length=25,  null=True)
    rel_8 = models.CharField(max_length=25,  null=True)

    fm_place = models.CharField(max_length=50,  null=True)

    # driver    
    name_dr = models.CharField(max_length=50,  null=True)
    driv_name = models.CharField(max_length=50,  null=True)
    

class tblFuel(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    ExpenseDt = models.DateField(blank=True, null=True)
    AmtClaimed = models.BigIntegerField(blank=True, null=True)  
    RecNumber = models.CharField(max_length=50,  null=True)
    AppAmt = models.BigIntegerField(blank=True, null=True)  
    VehNumber = models.CharField(max_length=50,  null=True)
    ClaimDt = models.DateTimeField(null=True)
    Decription = models.CharField(max_length=50,  null=True)
    ClaimNo = models.CharField(max_length=50,  null=True)
    remarks = models.CharField(max_length=50,  null=True)

    save_number = models.CharField(max_length=50, null=True, default=None)
    reminder_dt = models.DateTimeField(null=True)

class tblRoad(models.Model):
    empid = models.CharField(max_length=50,  null=True)
    ExpenseDt = models.DateField(blank=True, null=True)
    AmtClaimed = models.BigIntegerField(blank=True, null=True)  
    RecNumber = models.CharField(max_length=50,  null=True)
    AppAmt = models.BigIntegerField(blank=True, null=True)  
    VehNumber = models.CharField(max_length=50,  null=True)
    ClaimDt = models.DateTimeField(null=True)
    Decription = models.CharField(max_length=50,  null=True)
    ClaimNo = models.CharField(max_length=50,  null=True)
    remarks = models.CharField(max_length=50,  null=True)
    
    save_number = models.CharField(max_length=50, null=True, default=None)
    reminder_dt = models.DateTimeField(null=True)

class tblLTA(models.Model):

    empid = models.CharField(max_length=50,  null=True)
    ExpenseDt = models.DateField(blank=True, null=True)
    AmtClaimed = models.BigIntegerField(blank=True, null=True)  
    RecNumber = models.CharField(max_length=50,  null=True)
    AppAmt = models.BigIntegerField(blank=True, null=True)

    StDt = models.DateField(blank=True, null=True)
    EndDt = models.DateField(blank=True, null=True)
    Decription = models.CharField(max_length=50,  null=True) 
    Origin = models.CharField(max_length=50,  null=True)
    PlaceTravel = models.CharField(max_length=50,  null=True)

    FamDec = models.TextField(default=None)
    LastClaim = models.CharField(max_length=50,  null=True)
    ClaimDt = models.DateTimeField(null=True)
    ClaimNo = models.CharField(max_length=50,  null=True)
    remarks = models.CharField(max_length=50,  null=True)

    save_number = models.CharField(max_length=50, null=True, default=None)
    reminder_dt = models.DateTimeField(null=True)
    

class Drive(models.Model):

    empid = models.CharField(max_length=15)
    ExpenseDt = models.DateField()    
    RecNumber = models.CharField(max_length=50)
    AppAmt = models.BigIntegerField(blank=True, null=True)
    DriveSal = models.BigIntegerField()
    SalaryMonth = models.CharField(max_length=10)
    ClaimDt = models.DateTimeField()
    ClaimNo = models.CharField(max_length=50,  null=True)
    remarks = models.CharField(max_length=50,  null=True)

    save_number = models.CharField(max_length=50, null=True, default=None)
    reminder_dt = models.DateTimeField(null=True)

class tblClaimeMaster(models.Model):
    empid = models.CharField(max_length=15)
    emp_name = models.CharField(max_length=15, default=None)
    ClaimNo = models.CharField(max_length=50, null=True, blank=True)
    Fuel = models.BooleanField(null=True)
    Road = models.BooleanField(null=True)
    Insurance = models.BooleanField(null=True)
    Driver = models.BooleanField(null=True)
    LTA = models.BooleanField(null=True)
    LTC = models.BooleanField(null=True)
    SubDate = models.DateTimeField(null=True, blank=True)
    SaveDt = models.DateTimeField(null=True, blank=True)
    Status = models.CharField(max_length=25, null=True, blank=True)
    verL1Date = models.DateTimeField(null=True, blank=True)
    verL1User = models.CharField(max_length=50, null=True, blank=True)
    verL2Date = models.DateTimeField(null=True, blank=True)
    verL2User = models.CharField(max_length=50, null=True, blank=True)
    Remarks = models.TextField(null=True, blank=True)
    Sub2date = models.DateTimeField(null=True, blank=True)
    generationTime = models.DateTimeField(null=True, blank=True)
    ver2date = models.DateTimeField(null=True, blank=True)
    ver2user = models.CharField(max_length=50, null=True, blank=True)
    seqNo = models.IntegerField(null=True, blank=True)
    ResubReminder1 = models.DateTimeField(null=True, blank=True)
    ResubReminder2 = models.DateTimeField(null=True, blank=True)
    ResubReminder3 = models.DateTimeField(null=True, blank=True)




'''

class it_proof(models.Model):

    ita1stdt = models.DateField(blank=True, null=True)
    ita1enddt = models.DateField(blank=True, null=True)
    ita1 = models.BigIntegerField(blank=True, null=True)
    ita2stdt = models.DateField(blank=True, null=True)
    ita2enddt = models.DateField(blank=True, null=True)
    ita2 = models.BigIntegerField(blank=True, null=True)
    ita3stdt = models.DateField(null=True)
    ita3enddt = models.DateField(null=True)
    ita3 = models.BigIntegerField(null=True)
    ita4stdt = models.DateTimeField(null=True)
    ita4enddt = models.DateTimeField(null=True)
    ita4 = models.BigIntegerField(null=True)
    ita5stdt = models.DateField(null=True)
    ita5enddt = models.DateField(null=True)
    ita5 = models.BigIntegerField(null=True)

    ita1stdt_2 = models.DateTimeField(null=True)
    ita1enddt_2 = models.DateTimeField(null=True)
    ita2stdt_2 = models.DateTimeField(null=True)
    ita2enddt_2 = models.DateTimeField(null=True)
    ita3stdt_2 = models.DateTimeField(null=True)
    ita3enddt_2 = models.DateTimeField(null=True)
    ita4stdt_2 = models.DateTimeField(null=True)
    ita4enddt_2 = models.DateTimeField(null=True)
    ita5stdt_2 = models.DateTimeField(null=True)
    ita5enddt_2 = models.DateTimeField(null=True)
    

    itr1 = models.CharField(max_length=50, null=True)  
    ispan_decl = models.CharField(max_length=50, null=True)
    itd13 = models.BigIntegerField(null=True)
    ita13 = models.BigIntegerField(null=True)
    itr13 = models.CharField(max_length=50, null=True)
    itd14 = models.BigIntegerField(null=True)
    ita14 = models.BigIntegerField(null=True)
    itr14 = models.CharField(max_length=50, null=True)
    itd15 = models.BigIntegerField(null=True)
    ita15 = models.BigIntegerField(null=True)
    itr15 = models.CharField(max_length=50, null=True)
    itd16 = models.BigIntegerField(null=True)
    ita16 = models.BigIntegerField(null=True)
    itr16 = models.CharField(max_length=50, null=True)
    itd17 = models.BigIntegerField(null=True)
    ita17 = models.BigIntegerField(null=True)
    itr17 = models.CharField(max_length=50, null=True)
    itd18 = models.BigIntegerField(null=True)
    ita18 = models.BigIntegerField(null=True)
    itr18 = models.CharField(max_length=50, null=True)
    itd19 = models.BigIntegerField(null=True)
    ita19 = models.BigIntegerField(null=True)
    itr19 = models.CharField(max_length=50, null=True)
    itd20 = models.BigIntegerField(null=True)
    ita20 = models.BigIntegerField(null=True)
    itr20 = models.CharField(max_length=50, null=True)
    itd80ddb = models.BigIntegerField(null=True)
    ita80ddb = models.BigIntegerField(null=True)
    itr80ddb = models.CharField(max_length=50, null=True)
    itd21 = models.BigIntegerField(null=True)
    ita21 = models.BigIntegerField(null=True)
    itr21 = models.CharField(max_length=50, null=True)
    itd22 = models.BigIntegerField(null=True)
    ita22 = models.BigIntegerField(null=True)
    itr22 = models.CharField(max_length=50, null=True)
    itd23 = models.BigIntegerField(null=True)
    ita23 = models.BigIntegerField(null=True)
    itr23 = models.CharField(max_length=50, null=True)
    itd24 = models.BigIntegerField(null=True) #self 
    ita24 = models.BigIntegerField(null=True)
    itr24 = models.CharField(max_length=50, null=True)
    itd25 = models.BigIntegerField(null=True)
    ita25 = models.BigIntegerField(null=True) #non senior
    itr25 = models.CharField(max_length=50, null=True)
    itd25_1 = models.BigIntegerField(null=True) # medical senior 
    ita25_1 = models.BigIntegerField(null=True)
    itr25_1 = models.CharField(max_length=50, null=True)
    itd26 = models.BigIntegerField(null=True)
    ita26 = models.BigIntegerField(null=True)
    itr26 = models.CharField(max_length=50, null=True)
    itd27 = models.BigIntegerField(null=True)
    ita27 = models.BigIntegerField(null=True)
    itr27 = models.CharField(max_length=50, null=True)
    itd28 = models.BigIntegerField(null=True)
    ita28 = models.BigIntegerField(null=True)
    itr28 = models.CharField(max_length=50, null=True)
    itd80TTA = models.BigIntegerField(null=True)
    ita80TTA = models.BigIntegerField(null=True)
    itr80TTA = models.CharField(max_length=50, null=True)
    itdoth = models.BigIntegerField(null=True)
    itaoth = models.BigIntegerField(null=True)
    itroth = models.CharField(max_length=50, null=True)
    itd29 = models.BigIntegerField(null=True)
    ita29 = models.BigIntegerField(null=True)
    itr29 = models.CharField(max_length=50, null=True)
    itd30 = models.BigIntegerField(null=True)
    ita30 = models.BigIntegerField(null=True)
    itr30 = models.CharField(max_length=50, null=True)
    itd31 = models.BigIntegerField(null=True)
    ita31 = models.BigIntegerField(null=True)
    itd32 = models.BigIntegerField(null=True)
    ita32 = models.BigIntegerField(null=True)
    itd33 = models.BigIntegerField(null=True)
    ita33 = models.BigIntegerField(null=True)
    itd34 = models.BigIntegerField(null=True)
    ita34 = models.BigIntegerField(null=True)
    itdP1 = models.BigIntegerField(null=True)
    itaP1 = models.BigIntegerField(null=True)
    itrP1 = models.CharField(max_length=10, null=True)
    itdP2 = models.BigIntegerField(null=True)
    itaP2 = models.BigIntegerField(null=True)
    itrP2 = models.CharField(max_length=10, null=True)
    itdP3 = models.BigIntegerField(null=True)
    itaP3 = models.BigIntegerField(null=True)
    itrP3 = models.CharField(max_length=10, null=True)
    itdP4 = models.BigIntegerField(null=True)
    itaP4 = models.BigIntegerField(null=True)
    itrP4 = models.CharField(max_length=10, null=True)
    remarks = models.TextField(null=True)
    operator = models.CharField(max_length=50, null=True)
    sub1Complete = models.BooleanField(null=True)
    sub1Date = models.DateTimeField(null=True)
    itd1_2 = models.BigIntegerField(null=True)
    ita1_2 = models.BigIntegerField(null=True)
    city1_2 = models.CharField(max_length=50, null=True)
    itd2_2 = models.BigIntegerField(null=True)
    ita2_2 = models.BigIntegerField(null=True)
    city2_2 = models.CharField(max_length=50, null=True)
    itd3_2 = models.BigIntegerField(null=True)
    ita3_2 = models.BigIntegerField(null=True)
    city3_2 = models.CharField(max_length=50, null=True)
    itd4_2 = models.BigIntegerField(null=True)
    ita4_2 = models.BigIntegerField(null=True)
    city4_2 = models.CharField(max_length=50, null=True)
    itd5_2 = models.BigIntegerField(null=True)
    ita5_2 = models.BigIntegerField(null=True)
    city5_2 = models.CharField(max_length=50, null=True)
    itd6_2 = models.BigIntegerField(null=True)
    ita6_2 = models.BigIntegerField(null=True)
    city6_2 = models.CharField(max_length=50, null=True)
    itd7_2 = models.BigIntegerField(null=True)
    ita7_2 = models.BigIntegerField(null=True)
    city7_2 = models.CharField(max_length=50, null=True)
    itd8_2 = models.BigIntegerField(null=True)
    ita8_2 = models.BigIntegerField(null=True)
    city8_2 = models.CharField(max_length=50, null=True)
    itd9_2 = models.BigIntegerField(null=True)
    ita9_2 = models.BigIntegerField(null=True)
    city9_2 = models.CharField(max_length=50, null=True)
    itd10_2 = models.BigIntegerField(null=True)
    ita10_2 = models.BigIntegerField(null=True)
    city10_2 = models.CharField(max_length=50, null=True)
    itd11_2 = models.BigIntegerField(null=True)
    ita11_2 = models.BigIntegerField(null=True)
    city11_2 = models.CharField(max_length=50, null=True)
    itd12_2 = models.BigIntegerField(null=True)
    ita12_2 = models.BigIntegerField(null=True)
    city12_2 = models.CharField(max_length=50, null=True)
    itr1_2 = models.CharField(max_length=50, null=True)
    itd13_2 = models.BigIntegerField(null=True)
    ita13_2 = models.BigIntegerField(null=True)
    itr13_2 = models.CharField(max_length=50, null=True)
    itd14_2 = models.BigIntegerField(null=True)
    ita14_2 = models.BigIntegerField(null=True)
    itr14_2 = models.CharField(max_length=50, null=True)
    itd15_2 = models.BigIntegerField(null=True)
    ita15_2 = models.BigIntegerField(null=True)
    itr15_2 = models.CharField(max_length=50, null=True)
    itd16_2 = models.BigIntegerField(null=True)
    ita16_2 = models.BigIntegerField(null=True)
    itr16_2 = models.CharField(max_length=50, null=True)
    itd17_2 = models.BigIntegerField(null=True)
    ita17_2 = models.BigIntegerField(null=True)
    itr17_2 = models.CharField(max_length=50, null=True)
    itd18_2 = models.BigIntegerField(null=True)
    ita18_2 = models.BigIntegerField(null=True)
    itr18_2 = models.CharField(max_length=50, null=True)
    itd19_2 = models.BigIntegerField(null=True)
    ita19_2 = models.BigIntegerField(null=True)
    itr19_2 = models.CharField(max_length=50, null=True)
    itd20_2 = models.BigIntegerField(null=True)
    ita20_2 = models.BigIntegerField(null=True)
    itr20_2 = models.CharField(max_length=50, null=True)
    itd80ddb_2 = models.BigIntegerField(null=True)
    ita80ddb_2 = models.BigIntegerField(null=True)
    itr80ddb_2 = models.CharField(max_length=50, null=True)
    itd21_2 = models.BigIntegerField(null=True)
    ita21_2 = models.BigIntegerField(null=True)
    itr21_2 = models.CharField(max_length=50, null=True)
    itd22_2 = models.BigIntegerField(null=True)
    ita22_2 = models.BigIntegerField(null=True)
    itr22_2 = models.CharField(max_length=50, null=True)
    itd23_2 = models.BigIntegerField(null=True)
    ita23_2 = models.BigIntegerField(null=True)
    itr23_2 = models.CharField(max_length=50, null=True)
    itd24_2 = models.BigIntegerField(null=True)
    ita24_2 = models.BigIntegerField(null=True)
    itr24_2 = models.CharField(max_length=50, null=True)
    itd25_2 = models.BigIntegerField(null=True)
    ita25_2 = models.BigIntegerField(null=True)
    itr25_2 = models.CharField(max_length=50, null=True)
    itd25_12 = models.CharField(max_length=10, null=True)
    ita25_12 = models.CharField(max_length=10, null=True)
    itr25_12 = models.CharField(max_length=10, null=True)
    itd26_2 = models.CharField(max_length=50, null=True)
    ita26_2 = models.CharField(max_length=50, null=True)
    itr26_2 = models.CharField(max_length=50, null=True)
    itd27_2 = models.BigIntegerField(null=True)
    ita27_2 = models.BigIntegerField(null=True)
    itr27_2 = models.CharField(max_length=50, null=True)
    itd28_2 = models.BigIntegerField(null=True)
    ita28_2 = models.BigIntegerField(null=True)
    itr28_2 = models.CharField(max_length=50, null=True)
    itd80TTA_2 = models.BigIntegerField(null=True)
    ita80TTA_2 = models.BigIntegerField(null=True)
    itr80TTA_2 = models.CharField(max_length=50, null=True)
    itdoth_2 = models.BigIntegerField(null=True)
    itaoth_2 = models.BigIntegerField(null=True)
    itroth_2 = models.CharField(max_length=50, null=True)
    itd29_2 = models.BigIntegerField(null=True)
    ita29_2 = models.BigIntegerField(null=True)
    itr29_2 = models.CharField(max_length=50, null=True)
    itd30_2 = models.BigIntegerField(null=True)
    ita30_2 = models.BigIntegerField(null=True)
    itr30_2 = models.CharField(max_length=50, null=True)
    itd31_2 = models.BigIntegerField(null=True)
    ita31_2 = models.BigIntegerField(null=True)
    itd32_2 = models.BigIntegerField(null=True)
    ita32_2 = models.BigIntegerField(null=True)
    itd33_2 = models.BigIntegerField(null=True)
    ita33_2 = models.BigIntegerField(null=True)
    itd34_2 = models.BigIntegerField(null=True)
    ita34_2 = models.BigIntegerField(null=True)
    itdP1_2 = models.BigIntegerField(null=True)
    itaP1_2 = models.BigIntegerField(null=True)
    itrP1_2 = models.CharField(max_length=50, null=True)
    itdP2_2 = models.BigIntegerField(null=True)
    itaP2_2 = models.BigIntegerField(null=True)
    itrP2_2 = models.CharField(max_length=10, null=True)
    itdP3_2 = models.BigIntegerField(null=True)
    itaP3_2 = models.BigIntegerField(null=True)
    itrP3_2 = models.CharField(max_length=10, null=True)
    itdP4_2 = models.BigIntegerField(null=True)
    itaP4_2 = models.BigIntegerField(null=True)
    itrP4_2 = models.CharField(max_length=10, null=True)
    operator_2 = models.CharField(max_length=50, null=True)
    sub2Complete = models.BooleanField(null=True)
    sub2Date = models.DateTimeField(null=True)
    ver2Date = models.DateTimeField(null=True)
    exFlag2 = models.BooleanField(null=True)
    itd1_3 = models.BigIntegerField(null=True)
    ita1_3 = models.BigIntegerField(null=True)
    city1_3 = models.CharField(max_length=50, null=True)
    itd2_3 = models.BigIntegerField(null=True)
    ita2_3 = models.BigIntegerField(null=True)
    city2_3 = models.CharField(max_length=50, null=True)
    itd3_3 = models.BigIntegerField(null=True)
    ita3_3 = models.BigIntegerField(null=True)
    city3_3 = models.CharField(max_length=50, null=True)
    itd4_3 = models.BigIntegerField(null=True)
    ita4_3 = models.BigIntegerField(null=True)
    city4_3 = models.CharField(max_length=50, null=True)
    itd5_3 = models.BigIntegerField(null=True)
    ita5_3 = models.BigIntegerField(null=True)
    city5_3 = models.CharField(max_length=50, null=True)
    itd6_3 = models.BigIntegerField(null=True)
    ita6_3 = models.BigIntegerField(null=True)
    city6_3 = models.CharField(max_length=50, null=True)
    itd7_3 = models.BigIntegerField(null=True)
    ita7_3 = models.BigIntegerField(null=True)
    city7_3 = models.CharField(max_length=50, null=True)
    itd8_3 = models.BigIntegerField(null=True)
    ita8_3 = models.BigIntegerField(null=True)
    city8_3 = models.CharField(max_length=50, null=True)
    itd9_3 = models.BigIntegerField(null=True)
    ita9_3 = models.BigIntegerField(null=True)
    city9_3 = models.CharField(max_length=50, null=True)
    itd10_3 = models.BigIntegerField(null=True)
    ita10_3 = models.BigIntegerField(null=True)
    city10_3 = models.CharField(max_length=50, null=True)
    itd11_3 = models.BigIntegerField(null=True)
    ita11_3 = models.BigIntegerField(null=True)
    city11_3 = models.CharField(max_length=50, null=True)
    itd12_3 = models.BigIntegerField(null=True)
    ita12_3 = models.BigIntegerField(null=True)
    city12_3 = models.CharField(max_length=50, null=True)
    itr1_3 = models.CharField(max_length=50, null=True)
    itd13_3 = models.BigIntegerField(null=True)
    ita13_3 = models.BigIntegerField(null=True)
    itr13_3 = models.CharField(max_length=50, null=True)
    itd14_3 = models.BigIntegerField(null=True)
    ita14_3 = models.BigIntegerField(null=True)
    itr14_3 = models.CharField(max_length=50, null=True)
    itd15_3 = models.BigIntegerField(null=True)
    ita15_3 = models.BigIntegerField(null=True)
    itr15_3 = models.CharField(max_length=50, null=True)
    itd16_3 = models.BigIntegerField(null=True)
    ita16_3 = models.BigIntegerField(null=True)
    itr16_3 = models.CharField(max_length=50, null=True)
    itd17_3 = models.BigIntegerField(null=True)
    ita17_3 = models.BigIntegerField(null=True)
    itr17_3 = models.CharField(max_length=50, null=True)
    itd18_3 = models.BigIntegerField(null=True)
    ita18_3 = models.BigIntegerField(null=True)
    itr18_3 = models.CharField(max_length=50, null=True)
    itd19_3 = models.BigIntegerField(null=True)
    ita19_3 = models.BigIntegerField(null=True)
    itr19_3 = models.CharField(max_length=50, null=True)
    itd20_3 = models.BigIntegerField(null=True)
    ita20_3 = models.BigIntegerField(null=True)
    itr20_3 = models.CharField(max_length=50, null=True)
    itd80ddb_3 = models.BigIntegerField(null=True)
    ita80ddb_3 = models.BigIntegerField(null=True)
    itr80ddb_3 = models.CharField(max_length=50, null=True)
    itd21_3 = models.BigIntegerField(null=True)
    ita21_3 = models.BigIntegerField(null=True)
    itr21_3 = models.CharField(max_length=50, null=True)
    itd22_3 = models.BigIntegerField(null=True)
    ita22_3 = models.BigIntegerField(null=True)
    itr22_3 = models.CharField(max_length=50, null=True)
    itd23_3 = models.BigIntegerField(null=True)
    ita23_3 = models.BigIntegerField(null=True)
    itr23_3 = models.CharField(max_length=50, null=True)
    itd24_3 = models.BigIntegerField(null=True)
    ita24_3 = models.BigIntegerField(null=True)
    itr24_3 = models.CharField(max_length=50, null=True)
    itd25_3 = models.BigIntegerField(null=True)
    ita25_3 = models.BigIntegerField(null=True)
    itr25_3 = models.CharField(max_length=50, null=True)
    itd25_13 = models.BigIntegerField(null=True)
    ita25_13 = models.BigIntegerField(null=True)
    itr25_13 = models.CharField(max_length=50, null=True)
    itd26_3 = models.BigIntegerField(null=True)
    ita26_3 = models.BigIntegerField(null=True)
    itr26_3 = models.CharField(max_length=50, null=True)
    itd27_3 = models.BigIntegerField(null=True)
    ita27_3 = models.BigIntegerField(null=True)
    itr27_3 = models.CharField(max_length=50, null=True)
    itd28_3 = models.BigIntegerField(null=True)
    ita28_3 = models.BigIntegerField(null=True)
    itr28_3 = models.CharField(max_length=50, null=True)
    itd29_3 = models.BigIntegerField(null=True)
    ita29_3 = models.BigIntegerField(null=True)
    itr29_3 = models.CharField(max_length=50, null=True)
    itd30_3 = models.BigIntegerField(null=True)
    ita30_3 = models.BigIntegerField(null=True)
    itr30_3 = models.CharField(max_length=50, null=True)
    itd31_3 = models.BigIntegerField(null=True)
    ita31_3 = models.BigIntegerField(null=True)
    itd32_3 = models.BigIntegerField(null=True)
    ita32_3 = models.BigIntegerField(null=True)
    itd33_3 = models.BigIntegerField(null=True)
    ita33_3 = models.BigIntegerField(null=True)
    itd34_3 = models.BigIntegerField(null=True)
    ita34_3 = models.BigIntegerField(null=True)
    operator_3 = models.CharField(max_length=50, null=True)
    sub3Complete = models.BooleanField(null=True)
    itd80EE = models.BigIntegerField(null=True)
    ita80EE = models.BigIntegerField(null=True)
    itr80EE = models.CharField(max_length=50, null=True)
    itd80EE_2 = models.BigIntegerField(null=True)
    ita80EE_2 = models.BigIntegerField(null=True)
    itr80EE_2 = models.CharField(max_length=50, null=True)
    itd80EE_3 = models.BigIntegerField(null=True)
    ita80EE_3 = models.BigIntegerField(null=True)
    itr80EE_3 = models.CharField(max_length=50, null=True)
    sub3Date = models.DateTimeField(null=True)
    ver3Date = models.DateTimeField(null=True)
    exFlag3 = models.BooleanField(null=True)
    ita80TTA_3 = models.BigIntegerField(null=True)
    itr80TTA_3 = models.CharField(max_length=50, null=True)
    itaOth_3 = models.BigIntegerField(null=True)
    itroth_3 = models.CharField(max_length=50, null=True)
    itaP1_3 = models.BigIntegerField(null=True)
    itrP1_3 = models.CharField(max_length=50, null=True)
    itaP2_3 = models.BigIntegerField(null=True)
    itaP3_3 = models.BigIntegerField(null=True)
    itaP4_3 = models.BigIntegerField(null=True)
    operatorL3 = models.CharField(max_length=50, null=True)
    empDeclaration = models.BooleanField(null=True)
    itdSukSam = models.BigIntegerField(null=True)
    itaSukSam = models.BigIntegerField(null=True)
    itrSukSam = models.CharField(max_length=250, null=True)
    itdSukSam_2 = models.BigIntegerField(null=True)
    itaSukSam_2 = models.BigIntegerField(null=True)
    itdSukSam_3 = models.BigIntegerField(null=True)
    itaSukSam_3 = models.BigIntegerField(null=True)
    itdCCD = models.BigIntegerField(null=True)
    itaCCD = models.BigIntegerField(null=True)
    itrCCD = models.CharField(max_length=250, null=True)
    itd80CCD1 = models.BigIntegerField(null=True)
    ita80CCD1 = models.BigIntegerField(null=True)
    itr80CCD1 = models.CharField(max_length=10, null=True)  
    rd80ddb = models.CharField(max_length=50, null=True)
    ita80CCD1_3 = models.BigIntegerField(null=True)
    itdOth_3 = models.BigIntegerField(null=True)
    ita80CCD1_2 = models.BigIntegerField(null=True)
    
    itaCCD_2 = models.BigIntegerField(null=True)
    itrSukSam_2 = models.CharField(max_length=50, null=True)
    itrCCD_2 = models.CharField(max_length=50, null=True)
    itr80CCD1_2 = models.CharField(max_length=50, null=True)
    itrSukSam_3 = models.CharField(max_length=10, null=True)
    itaCCD_3 = models.BigIntegerField(null=True)
    itrCCD_3 = models.CharField(max_length=10, null=True)
    itr80CCD1_3 = models.CharField(max_length=30, null=True)  
    LoanLenderName = models.CharField(max_length=250, null=True)
    LoanLenderPan = models.CharField(max_length=50, null=True)
    itdInt80ee = models.BigIntegerField(null=True)
    itaInt80ee = models.BigIntegerField(null=True)
    itdloan80ee = models.BigIntegerField(null=True)
    loanDt80ee = models.DateTimeField(null=True)
    LenderName80ee = models.CharField(max_length=250, null=True)
    LenderPAN80ee = models.CharField(max_length=50, null=True)
    propertyVal = models.BigIntegerField(null=True)
    LetLenderName = models.CharField(max_length=250, null=True)
    LetLenderPan = models.CharField(max_length=15, null=True)
    rdRentFullYear = models.CharField(max_length=10, null=True)
    rdChangeRent = models.CharField(max_length=10, null=True)
    rdNps = models.CharField(max_length=10, null=True)
    rd80D = models.CharField(max_length=10, null=True) 
    italoan80ee = models.IntegerField(null=True)
    itapropertyVal = models.IntegerField(null=True)
    itdLTA = models.IntegerField(null=True)
    itaLTA = models.IntegerField(null=True)
    itdMed = models.IntegerField(null=True)
    itaMed = models.IntegerField(null=True)
    itdVehicle = models.IntegerField(null=True)
    itaVehicle = models.IntegerField(null=True)
    rd80EE = models.BooleanField(null=True)
    rdHRA = models.BooleanField(null=True)  
    totalRent = models.IntegerField(null=True)
    rdIsMailCorrect = models.BooleanField(null=True)  
    rd80c = models.BooleanField(null=True)
    rd80ccd1b = models.BooleanField(null=True)
    rd80other = models.BooleanField(null=True)
    itdPreventive = models.IntegerField(null=True)
    rdOtherInc = models.BooleanField(null=True)
    itd80eeOtherLender = models.CharField(max_length=250, null=True)
    rdPrevious = models.BooleanField(null=True)
    rdself = models.BooleanField(null=True)
    itdLetOtherLender = models.CharField(max_length=250, null=True)
    drpLetLender = models.CharField(max_length=250, null=True)
    itdSelfOtherLender = models.CharField(max_length=250, null=True)
    drpSelfLender = models.CharField(max_length=250, null=True)
    rd80tta = models.BooleanField(null=True)
    rd80u = models.BooleanField(null=True)
    rd80dd = models.BigIntegerField(null=True)
    timestamp = models.DateTimeField(null=True)
    PRANno = models.CharField(max_length=30, null=True)
    drp80eeLender = models.CharField(max_length=250, null=True)
    pincode6 = models.CharField(max_length=10, null=True)
    pincode7 = models.CharField(max_length=10, null=True)
    pincode8 = models.CharField(max_length=10, null=True)
    pincode9 = models.CharField(max_length=10, null=True)
    pincode10 = models.CharField(max_length=10, null=True)
    pincode11 = models.CharField(max_length=10, null=True)
    pincode12 = models.CharField(max_length=10, null=True)
    itaPreventive = models.BigIntegerField(null=True)
    itrpreventive = models.CharField(max_length=10, null=True)
    itaPreventive_2 = models.BigIntegerField(null=True)
    itaPreventive_3 = models.BigIntegerField(null=True)
    itrPrev_2 = models.CharField(max_length=10, null=True)
    itrPrev_3 = models.CharField(max_length=10, null=True)
    gender = models.CharField(max_length=15, null=True)
    CompanyName = models.CharField(max_length=50, null=True)
    status = models.CharField(max_length=50, null=True)
    itrpreventive_2 = models.BigIntegerField(null=True)
    itaPrev_2 = models.BigIntegerField(null=True)
    itrlta = models.BigIntegerField(null=True)
    itaPrev_3 = models.BigIntegerField(null=True)
    itrPreventive_3 = models.BigIntegerField(null=True)
    italta_2 = models.BigIntegerField(null=True)
    itrlta_2 = models.BigIntegerField(null=True)
    sent = models.BooleanField(null=True)
    loanDt80eeA = models.DateField(null=True)
    itdloan80eeA = models.BigIntegerField(null=True)
    itdInt80eeA = models.BigIntegerField(null=True)
    ita80EEA = models.BigIntegerField(null=True)
    itr80EEA = models.CharField(max_length=50, null=True)
    ita80EEA_2 = models.BigIntegerField(null=True)
    itr80EEA_2 = models.CharField(max_length=50, null=True)
    ita80EEA_3 = models.BigIntegerField(null=True)
    itr80EEA_3 = models.CharField(max_length=50, null=True)
    loanDt80eeB = models.DateField(null=True)
    itdloan80eeB = models.BigIntegerField(null=True)
    itdInt80eeB = models.BigIntegerField(null=True)
    ita80EEB = models.BigIntegerField(null=True)
    itr80EEB = models.CharField(max_length=50, null=True)
    ita80EEB_2 = models.BigIntegerField(null=True)
    itr80EEB_2 = models.CharField(max_length=50, null=True)
    ita80EEB_3 = models.BigIntegerField(null=True)
    itr80EEB_3 = models.CharField(max_length=50, null=True)
    LenderName80eeA = models.CharField(max_length=50, null=True)
    LenderPAN80eeA = models.CharField(max_length=50, null=True)
    LenderName80eeB = models.CharField(max_length=50, null=True)
    LenderPAN80eeB = models.CharField(max_length=50, null=True)
    propertyVal80eeA = models.BigIntegerField(null=True)
    propertyVal80eeB = models.BigIntegerField(null=True)
    itd80eeAOtherLender = models.CharField(max_length=250, null=True)
    itd80eeBOtherLender = models.CharField(max_length=250, null=True)
    rd80EEA = models.BooleanField(null=True)
    rd80EEB = models.BooleanField(null=True)
    Admin_TS = models.DateTimeField(null=True)
    Admin_FLG = models.BooleanField(null=True)
    Admin_op = models.CharField(max_length=50, null=True)
    FLG0580 = models.BooleanField(null=True)
    FLG0581 = models.BooleanField(null=True)
    FLG0581H2 = models.BooleanField(null=True)
    FLG0581H3 = models.BooleanField(null=True)
    FLG0581H4 = models.BooleanField(null=True)
    FLG0581H5 = models.BooleanField(null=True)
    FLG058401S = models.BooleanField(null=True)
    FLG058401L = models.BooleanField(null=True)
    FLG058402 = models.BooleanField(null=True)
    FLG0585 = models.BooleanField(null=True)
    FLG0586 = models.BooleanField(null=True)
    GENTS0580 = models.DateTimeField(null=True)
    GENTS0581 = models.DateTimeField(null=True)
    GENTS0581H2 = models.DateTimeField(null=True)
    GENTS0581H3 = models.DateTimeField(null=True)
    GENTS0581H4 = models.DateTimeField(null=True)
    GENTS0581H5 = models.DateTimeField(null=True)
    GENTS058401S = models.DateTimeField(null=True)
    GENTS058401L = models.DateTimeField(null=True)
    GENTS058402 = models.DateTimeField(null=True)
    GENTS0585 = models.DateTimeField(null=True)
    GENTS0586 = models.DateTimeField(null=True)
    FLG0581H01_2 = models.BooleanField(null=True)
    FLG0581H02_3 = models.BooleanField(null=True)
    FLG0581H03_4 = models.BooleanField(null=True)
    FLG0581H04_5 = models.BooleanField(null=True)
    FLG0581H05_6 = models.BooleanField(null=True)
    GENTS0581H01_2 = models.DateTimeField(null=True)
    GENTS0581H02_3 = models.DateTimeField(null=True)
    GENTS0581H03_4 = models.DateTimeField(null=True)
    GENTS0581H04_5 = models.DateTimeField(null=True)
    GENTS0581H05_6 = models.DateTimeField(null=True)

'''