# Generated by Django 5.0.1 on 2024-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_it_proof_80_other_ded80_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_proof_basic',
            name='veh_reg_num',
        ),
        migrations.AddField(
            model_name='it_proof_80_other',
            name='veh_reg_num',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
