# Generated by Django 5.0.1 on 2024-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_it_proof_basic_veh_reg_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_proof_income_loss',
            name='place_80ee',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='it_proof_income_loss',
            name='place_80eea',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
